import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnableParallel, RunnablePassthrough, RunnableSequence
from langchain_core.prompts import ChatPromptTemplate
from utils.model_setup import get_model
from dotenv import load_dotenv
load_dotenv()
model = get_model()
parser = StrOutputParser()

# --- What is RunnablePassthrough? ---
# RunnablePassthrough simply forwards its input unchanged.
# On its own that sounds useless, but it shines inside RunnableParallel
# when you want to pass the original input alongside a transformed version.
#
# Common pattern:
#   RunnableParallel(
#       original=RunnablePassthrough(),   # keeps the raw input
#       transformed=some_chain,           # processes the input
#   )

# --- Example: Generate a tweet AND keep the original topic ---
# Without RunnablePassthrough we'd lose access to the raw topic after
# the model generates its output.  Here we preserve it.

tweet_prompt = ChatPromptTemplate.from_messages([
    ("system", "You are a social media expert. Keep responses short and concise."),
    ("human", "Write a catchy tweet about {topic}. Just the tweet, nothing else."),
])
tweet_chain = RunnableSequence(tweet_prompt, model, parser)

# RunnablePassthrough forwards the entire input dict {"topic": "..."} unchanged,
# while tweet_chain processes it through the LLM.
chain = RunnableParallel(
    original_input=RunnablePassthrough(),
    tweet=tweet_chain,
)

result = chain.invoke({"topic": "artificial intelligence"})

# Output looks like:
# {
#   "original_input": {"topic": "artificial intelligence"},   ← passed through unchanged
#   "tweet": "🤖 AI isn't just the future — it's the NOW..."  ← generated by the LLM
# }

print("=" * 50)
print("📥  ORIGINAL INPUT (via RunnablePassthrough):")
print(result["original_input"])
print("-" * 50)
print("🐦  GENERATED TWEET:")
print(result["tweet"])
print("=" * 50)

# --- Example 2: RunnablePassthrough.assign() ---
# .assign() is a shortcut that passes the input through AND adds new keys.
# It's equivalent to RunnableParallel(original_keys..., new_key=some_chain)
# but without having to manually forward every existing key.

summary_prompt = ChatPromptTemplate.from_messages([
    ("system", "You are a helpful assistant. Keep responses short and concise."),
    ("human", "Summarize this topic in one sentence: {topic}"),
])
summary_chain = RunnableSequence(summary_prompt, model, parser)

# .assign() keeps all original keys (like "topic") and adds "summary"
chain2 = RunnablePassthrough.assign(summary=summary_chain)

result2 = chain2.invoke({"topic": "quantum computing"})

# Output looks like:
# {
#   "topic": "quantum computing",                              ← original key kept
#   "summary": "Quantum computing harnesses quantum mechanics..." ← new key added by .assign()
# }

print("\n" + "=" * 50)
print("📥  FULL OUTPUT (via RunnablePassthrough.assign):")
print(f"  topic:   {result2['topic']}")
print(f"  summary: {result2['summary']}")
print("=" * 50)
